### ISSUE TITLE
Does it fallback to gzip if browser doesn't support br?

### ISSUE THREAD

**Issue by denny64** [illagrenan/django-brotli#105]

**Comment by illagrenan** [comment]
I apologize for delayed response.

`django-brotli` middleware works only and only if:

1. The client supports `br` (indicated in `Accept-Encoding` header).
2. The response does not have a `Content-Encoding` header set. 

See full condition here: https://github.com/illagrenan/django-brotli/blob/master/django_brotli/middleware.py#L31-L32

So the answer is: **no, this middleware has no fallback to GZIP**.

If you want to support both `BR` and `GZIP` (as a fallback), I recommend using both middleware classes as follows:

```py
MIDDLEWARE = [
  # ...
  'django_brotli.middleware.BrotliMiddleware',
  'django.middleware.gzip.GZipMiddleware'
  # ...
]
```

If the client does not support `BR`, `BrotliMiddleware` will do nothing. Then comes `GZipMiddleware`, which can apply the appropriate compression.
