### ISSUE TITLE
Use Github Actions for CI and for publishing on PyPI

### ISSUE THREAD

**Issue by illagrenan** [illagrenan/django-brotli#108]
Copy the configuration from this project: https://github.com/illagrenan/django-asgi-lifespan

**Comment by ddelange** [comment]
hi @illagrenan 👋 is this a blocker to release the latest changes from master to pypi?

fwiw here's an [example](https://github.com/ddelange/mapply/blob/0.1.17/.github/workflows/CD.yml) that uploads to pypi when you release a Github (pre)release using [your repo's github secrets](https://github.com/illagrenan/django-brotli/settings/secrets/actions)

**Comment by ddelange** [comment]
master works nicely for django 4.1.2 btw :) as long as you define this middleware _after_ the gzip middleware, br will be preferred when client accepts them all 💪

**Comment by illagrenan** [comment]
I just published a new release (https://github.com/illagrenan/django-brotli/releases/tag/v0.2.1) on PyPI with your changes. Thanks again for the pull request.

This repository could use some improvements. I'm using Github Actions (https://github.com/illagrenan/django-asgi-lifespan) in my other project – I hope to find time to update this project soon

**Comment by illagrenan** [comment]
Done 🚀
